ame: Test Pipeline1
on: push


jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Step1
      run: echo "Step1 executed"

    - name: Step2
      run: echo "Step2 Executed"

    - name: Checkout the code
      uses: actions/checkout@v6.0.1

    - name: Read the content of the code repo
      run: cat three.txt
